name: Homework CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:

    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Test with Gradle
      run: |
        mkdir %HOMEDRIVE%%HOMEPATH%\.gradle
        ./gradlew build test 
        if ERRORLEVEL 1 (exit 1)
    
    - name: Generate coverage report
      run: ./gradlew jacocoTestReport

    - name: Check coverage
      run: |
        ./gradlew jacocoTestCoverageVerification || exit 2
    - name: Build Gradle
  
      run: |
        ./gradlew build
        if ERRORLEVEL 1 (exit 2)
        
