name: Homework CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        
    - name: Build 
      run: |
        mkdir %HOMEDRIVE%%HOMEPATH%\.gradle
        ./gradlew.bat clean build

    - name: Generate JaCoCo report
      run: ./gradlew.bat jacocoTestReport

    - name: Verify JaCoCo coverage
      run: ./gradlew.bat jacocoTestCoverageVerification
      
    
