name: Homework CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildGradle:
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Check coverage
        run: |
          mkdir %HOMEDRIVE%%HOMEPATH%\.gradle
            ./gradlew build
            
  test:

    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        
    - name: Test with Gradle
      run: |
        mkdir %HOMEDRIVE%%HOMEPATH%\.gradle
        ./gradlew build test
  
  checkCoverage:
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          
      - name: Check coverage
        run: |
            mkdir %HOMEDRIVE%%HOMEPATH%\.gradle
            ./gradlew jacocoTestCoverageVerification
    
          
      
    
