name: Homework CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        
    - name: Test 
      run: |
        mkdir %HOMEDRIVE%%HOMEPATH%\.gradle
        ./gradlew test
  
  checkCoverage:
    needs: [test]
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          
      - name: Check coverage
        run: |
            mkdir %HOMEDRIVE%%HOMEPATH%\.gradle
            ./gradlew jacocoTestCoverageVerification
            
  buildGradle:
    needs: [test, checkCoverage]
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Check coverage
        run: |
          mkdir %HOMEDRIVE%%HOMEPATH%\.gradle
            ./gradlew build
            
          
      
    
