name: Homework CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew build

  test_failure:

    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Test failure
      run: echo "package com.example; import org.junit.jupiter.api.Test; import static org.junit.jupiter.api.Assertions.fail; public class FailingTest { @Test public void testFailure() { fail(\"Тест выдающий ошибку\"); } }" > src/test/java/com/example/BoundaryServiceTest.java

    - name: Build with Gradle
      run: ./gradlew build
      continue-on-error: true

  coverage_failure:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Coverage failure
      run: echo "package com.example; public class UncoveredCode { public void uncoveredMethod() { /* Метод непокрытый тестами */ } }" > src/main/java/com/example/BoundaryServiceTest.java

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run JaCoCo test coverage
      run: ./gradlew jacocoTestReport
      continue-on-error: true
